# main.py
"""
Sovereign Engine - Main Entry Point
Advanced PDF Matrix Extraction Engine for Vehicle Design & H-Point Analysis
"""

import sys
from pathlib import Path
import asyncio
from datetime import datetime

# Add root to path for imports
root = Path(__file__).parent
sys.path.insert(0, str(root))

print("🔧 Initializing Sovereign Engine...\n")

try:
    from sovereign_engine import SovereignEngine
    print("✅ SovereignEngine imported successfully!\n")
except Exception as e:
    print(f"❌ Failed to import SovereignEngine: {e}")
    import traceback
    traceback.print_exc()
    sys.exit(1)


async def main():
    """Main execution function"""
    try:
        print("🚀 Creating SovereignEngine instance...")
        engine = SovereignEngine()
        print("✅ SovereignEngine initialized successfully!")

        # Show engine status
        status = engine.get_status()
        print(f"📊 Engine Status          : {status.get('status', 'UNKNOWN')}")
        print(f"🧠 Memory Cache Size     : {status.get('cache_size', 0)} pages")
        print(f"🧬 Embedder Ready        : {status.get('embedder_ready', False)}\n")

        # Get PDF path from user
        pdf_input = input("📂 Enter PDF file path: ").strip('"\' ')

        if not pdf_input:
            print("⚠️ No file path provided.")
            return

        pdf_path = Path(pdf_input).resolve()

        if not pdf_path.exists():
            print(f"❌ File not found: {pdf_path}")
            return

        if not pdf_path.suffix.lower() == '.pdf':
            print("⚠️ File is not a PDF.")
            return

        print(f"\n⏳ Processing: {pdf_path.name} ...\n")

        # Process the PDF
        result = await engine.process_pdf(str(pdf_path), domain="Vehicle_Design")

        if result.get("status") == "SUCCESS":
            total_pages = result.get('total_pages', 0)
            total_matrices = result.get('total_matrices', 0)
            execution_time = result.get('execution_time', 0)

            print("\n" + "="*70)
            print("✅ Processing Completed Successfully!")
            print("="*70)
            print(f"   • Total Pages          : {total_pages}")
            print(f"   • Matrices Extracted   : {total_matrices}")
            print(f"   • Processing Time      : {execution_time:.2f} seconds")
            print("="*70 + "\n")

            # Save report
            save_markdown_report(result, pdf_path.name)

        else:
            print(f"❌ Processing failed: {result.get('error', 'Unknown error')}")

    except KeyboardInterrupt:
        print("\n\n⛔ Process interrupted by user.")
    except Exception as e:
        print(f"🛑 Unexpected error: {e}")
        import traceback
        traceback.print_exc()


def save_markdown_report(result: dict, filename: str):
    """Save a professional Markdown report"""
    try:
        report_dir = Path("reports")
        report_dir.mkdir(parents=True, exist_ok=True)

        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        md_path = report_dir / f"Report_{Path(filename).stem}_{timestamp}.md"

        total_pages = result.get('total_pages', 0)
        total_matrices = result.get('total_matrices', 0)
        exec_time = result.get('execution_time', 0)

        content = f"""# Sovereign Engine Processing Report

**File:** {filename}  
**Date:** {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}  
**Status:** ✅ Success

## 📊 Summary Statistics

| Metric                        | Value                    |
|-------------------------------|--------------------------|
| Total Pages                   | **{total_pages}**        |
| Extracted Matrices            | **{total_matrices}**     |
| Processing Time               | {exec_time:.2f} seconds  |
| Domain                        | Vehicle Design (H-Point) |

## 📋 Results Overview
- **Document Type:** Vehicle Design / H-Point Analysis
- **Extraction Quality:** High
- **Technical Pages:** Approximately {max(total_pages - 8, 0)}

---
**Generated by Sovereign Engine v2.0**
"""

        with open(md_path, "w", encoding="utf-8") as f:
            f.write(content)
        
        print(f"📄 Report saved successfully:")
        print(f"   → {md_path}")
        return True

    except Exception as e:
        print(f"\n🛑 Error while saving report: {e}")
        import traceback
        traceback.print_exc()
        return False


if __name__ == "__main__":
    asyncio.run(main())